# Generated by Django 4.2.11 on 2026-08-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0012_auto_20181031_0913"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptoms", models.CharField(max_length=1000)),
                ("prediction", models.CharField(max_length=255)),
                ("priority", models.CharField(max_length=20)),
                ("confidence", models.FloatField(default=0.0)),
                ("explanation", models.CharField(max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="server.account",
                    ),
                ),
            ],
        ),
    ]
