# Generated by Django 4.2.11 on 2026-08-30 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0013_aianalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="ai_analysis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment",
                to="server.aianalysis",
            ),
        ),
    ]
