# Generated by Django 4.2.11 on 2026-08-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0014_appointment_ai_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysis",
            name="possible_conditions",
            field=models.JSONField(default=list),
        ),
    ]
