# Generated by Django 4.2.11 on 2026-08-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0015_aianalysis_possible_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysis",
            name="doctor_review",
            field=models.CharField(default="PENDING", max_length=20),
        ),
        migrations.AddField(
            model_name="aianalysis",
            name="final_diagnosis",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="aianalysis",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aianalysis",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_reviews",
                to="server.account",
            ),
        ),
    ]
